#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

function link_dotfile() {
    local dotfile=$1
    local link=~/.${dotfile}
    local name
    name=$(basename "${link}")

    if [[ -L $link ]]; then
        echo "✅ ${name}"
    elif [[ -f $link ]]; then
        echo "❌ ${name} exists"
    else
        echo "🛠  Linking ${name}"
        ln -s "${DIR}/${dotfile}" "${link}" || exit 1
    fi
}

dotfiles=( vimrc gitignore gitconfig )
for dotfile in "${dotfiles[@]}"
do
    link_dotfile "${dotfile}"
done

echo "🎉"
exit 0
